version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  # sempre que precisar parar os container rode o comando:
  # docker compose down --volumes
  
  db:
    image: postgres:latest
    container_name: my-postgres-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: subscriberdata
    ports:
      - "5432:5432"
