version: '3'

services:
  app:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # networks:
    #   - my-network